#!/usr/bin/env python3

import sys
import sqlite3
from datetime import date
from enum import Enum

class Table(Enum):
    applications = 1
    companies = 2
    contacts = 3 
    events = 4

def applications(cursor, date):
    cursor.execute("SELECT count(*) FROM applications;")
    app_id = int(cursor.fetchone()[0]) + 1
    company_name = input("Enter company name: ")
    position = input("Enter position title: ")
    department = input("Enter department or team: ")
    location = input("Enter location: ")
    app_date = date 
    salary = float(input("Enter salary (float): "))
    status = "Applied"
    status_date = date 
    posting_url = input("Enter job posting url: ")
    where_applied = input("Enter where applied: ")
    resume = input("Enter resume version: ")
    referral = input("Enter referral name: ")
    if referral == "":
        referral = None
    interview_date = None 
    follow_up_date = None 
    offer_details = None 
    notes = input("Enter notes: ")
    if notes == "":
        notes = None
    last_updated = date 
    start_date = input("Enter start date: ")
    if start_date == "":
        start_date = "06-01-2025"
    end_date = input("Enter end date: ")
    if end_date == "":
        end_date = "08-01-2025"
    job_board = input("Enter job board: ")

    data = [ app_id, company_name, position, department, location, app_date,
            salary, status, start_date, posting_url, where_applied, resume,
            referral, interview_date, follow_up_date, offer_details, notes,
            last_updated, start_date, end_date, job_board ]
    assert len(data) == 21, "Data invalid"

    cursor.execute("""
    INSERT INTO applications VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, data)


def companies(cursor, date):
    company_name = input("Enter company name: ")
    industry = input("Enter industry: ")
    headquarters = input("Enter headquarters location: ")
    size = input("Enter size (small, medium, large): ")
    website = input("Enter website url: ")
    careers_page = input("Enter careers page url: ")
    contact_email = input("Enter contact email: ")
    contact_person = input("Enter contact person name: ")
    notes = input("Enter notes: ")
    is_target_str = input("Is target? (y/n): ")
    is_target = False
    if is_target_str == "y":
        is_target = True
    last_updated = date

    data = [ company_name, industry, headquarters, size, website, careers_page,
            contact_email, contact_person, notes, is_target, last_updated ]
    assert len(data) == 11, "Data invalid"

    cursor.execute("""
    INSERT INTO companies VALUES(?,?,?,?,?,?,?,?,?,?,?)
    """, data)

def contacts(cursor, date):
    contact_name = input("Enter contact name: ")
    company_name = input("Enter company name: ")
    linkedin= input("Enter LinkedIn: ")
    email = input("Enter email: ")
    phone_number = input("Enter phone_number: ")
    if phone_number != "":
        try:
            phone_number = int(phone_number)
        except:
            print("Invalid phone number")
            sys.exit(1)
    last_contacted = input("Enter last contacted date (\'DD-MM-YYYY\' or t for today): ")
    if last_contacted == "t":
        last_contacted = date 
    where_met = input("Where did we meet?: ")

    data = [ contact_name, company_name, linkedin, email, phone_number,
            last_contacted, where_met ]
    assert len(data) == 7, "Data invalid"

    cursor.execute("""
    INSERT INTO contacts VALUES(?,?,?,?,?,?,?)
    """, data)


def events(cursor, date):
    pass

def main():
    print("1: applications")
    print("2: companies")
    print("3: contacts")
    print("4: events")
    table = input("Insert into which table? Enter: ")
    try:
        table = int(table)
    except:
        print("Invalid input (must be integer)")
        sys.exit(1)

    conn = sqlite3.connect('applications.db')
    cursor = conn.cursor()

    today = date.today()
    date_str = f"{today.month}-{today.day}-{today.year}"

    match table:
        case Table.applications.value:
            applications(cursor, date_str)
        case Table.companies.value:
            companies(cursor, date_str)
        case Table.contacts.value:
            contacts(cursor, date_str)
        case Table.events.value:
            events(cursor, date_str)
        case _:
            print("Invalid input (must be 1-4)")
            sys.exit(2)
    
    conn.commit()

if __name__=="__main__":
    main()
